# ========================================================================
# Script Title: Extract & wrangle UKB baseline assessment data [baseline_ scripts 2 of 3]
# Author: Sam Ip
# - Preceded by baseline_0_first_cancer.r
# - Extracts and processes UKB baseline assessment predictors
# - Applies eligibility filters, including first-degree relative exclusions
# ========================================================================
rm(list=ls())

# Define Directories ----
dir_ACED <- "~/ACED-CRC-modelling"
setwd(file.path(dir_ACED, "CRC_analysis"))
scripts_modelling_dir <- file.path(dir_ACED, "CRC_analysis", "modelling")

# Load Configurations ----
source(file.path(scripts_modelling_dir, "hpc_config.r"))

# Identify Relevant UKB Fields ----
pheno_nums <- names(fread(fpath_baseline, nrows = 1))
pheno_nums_unique <- unique(sub("\\-.*", "", pheno_nums)) # Extract unique field numbers

# Extract fields of interest from UKB baseline assessment
baseline_fields <- fread(fpath_codelist_ukb_baseline)
df_baseline <- get_baselinefields(fpath_baseline, baseline_fields) %>% 
  dplyr::select("eid", names(df_baseline)[grepl("-0", names(df_baseline))]) # Keep only baseline (initial assessment) fields


# Remove columns with only NA values
df_baseline <- df_baseline %>% dplyr::select(names(df_baseline)[as.vector(colSums(is.na(df_baseline)) < nrow(df_baseline))])
sort(names(df_baseline))


# Remove Unnecessary Covariates ----
df_baseline <- df_baseline %>% 
  dplyr::select( names(df_baseline)[! grepl(
    "^death|^edu_numyrs|^cancer|^birth_month|^physactivity|^ab|CRP|platelets|haematocrit_perc|Hb_conc", 
    names(df_baseline))])
sort(names(df_baseline))


# Wrangle predictors ----

### BMI (from Xin's UKB dataset) ----
fpath_xin <- "/store/cap12_vol2/gwas/biobank/phenotypes/update_jan21/ukb45115.tab" #Xin's UKB dataset
pheno_nums_xin <- names(fread(fpath_xin,nrows=1))
field_nums_xin <- pheno_nums_xin[grepl(paste0("^f.21001."), pheno_nums_xin)]
baseline_xin <- fread(fpath_xin, select=c("f.eid", field_nums_xin))
names(baseline_xin) <- names(baseline_xin) %>% sub("f.21001.", "bmi-", .) %>% sub("f.", "", .)
### Merge BMI data with our baseline data
key <- fread(fpath_key_fam) %>% dplyr::rename(eid=Cambridge_ID, joe_eid=UCL_ID)
baseline_xin <- merge(x = baseline_xin, y = key, by = "eid", all.x = TRUE)%>% 
  dplyr::select(!eid) %>% dplyr::rename(eid=joe_eid) %>% dplyr::filter(!is.na(eid)) 
baseline_xin <- baseline_xin %>% mutate(across(eid, as.character))
df_baseline <- merge(x = df_baseline, y = baseline_xin, by = "eid", all.x = TRUE)
colnames_bmi <- df_baseline %>% dplyr::select(grep_colnames("bmi-", df_baseline)) %>% filter(is.na(`bmi-0.0`)) %>% names()
df_baseline$bmi <- na.fill(df_baseline$`bmi-0.0`, median(df_baseline$`bmi-0.0`, na.rm=TRUE)) #use only bmi-0.0, fill na with median 0.0
df_baseline <- df_baseline %>% dplyr::select(!colnames_bmi)

### First cancer and death ----
df_first_cancer <- read_parquet(file.path(res_dir, "df_first_cancer.parquet")) # Generated by baseline_0_first_cancer.r
df_baseline <- merge(x = df_baseline, y = df_first_cancer, by = "eid", all.x = TRUE) %>% 
  dplyr::rename(date_firstcancer_or_death = censor_date)


# Apply Filters ----
### Exclude first-degree relatives ----
firstdeg_excl <- fread(fpath_first_deg_relatives, select = c("ukbid", "first_degree_relative_exclusion_list")) %>%
  filter(first_degree_relative_exclusion_list == 1) 
key <- fread(fpath_key_fam) %>% dplyr::rename(ukbid=Cambridge_ID, eid=UCL_ID)
firstdeg_excl <- merge(x = firstdeg_excl, y = key, by = "ukbid", all.x = TRUE)
df_baseline <- df_baseline %>% dplyr::filter(!(eid %in% firstdeg_excl$eid))

### Remove individuals without attendance date ----
df_baseline <- df_baseline %>% dplyr::filter(!is.na(`date_attendassessmentcentre-0.0`))

### Remove individuals with cancer/death before baseline ----
firstcancer_or_death_before_v0 <- df_baseline %>% dplyr::filter(date_firstcancer_or_death <= `date_attendassessmentcentre-0.0`)
df_baseline <-  df_baseline %>% dplyr::anti_join(firstcancer_or_death_before_v0) 


# Additional predictors in baseline_02
